sudo:
  false

language:
  python

python:
  - 2.7

services:
  - docker

install:
  - make install

before_script:
  - make restore_schema $TEST_WAREHOUSE_URL ./tests/dbs/warehouse_schema_dump.sql True
  - make restore_schema $TEST_DATABASE_URL ./tests/dbs/opentrials_api_schema_dump.sql True

script:
  - make test
  - make build

deploy:
  - provider: script
    script: make push
    on:
      branch: master
