sudo:
  false

language:
  python

python:
  - 2.7

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/opentrials_api_test
    - TEST_WAREHOUSE_URL=postgres://postgres@localhost:5432/opentrials_warehouse_test

addons:
  postgresql: "9.4"

services:
  - docker
  - postgresql

install:
  - make install

before_script:
  - psql -c 'create database opentrials_api_test;' -U postgres
  - psql -c 'create database opentrials_warehouse_test;' -U postgres
  - make restore_schema $TEST_WAREHOUSE_URL ./tests/dbs/warehouse_schema_dump.sql True
  - make restore_schema $TEST_DATABASE_URL ./tests/dbs/opentrials_api_schema_dump.sql True

script:
  - make test
  - make build

deploy:
  - provider: script
    script: make push
    on:
      branch: master
