sudo:
  false

language:
  python

python:
  - 2.7

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/opentrials_api_test
    - TEST_WAREHOUSE_URL=postgres://postgres@localhost:5432/opentrials_warehouse_test

addons:
  postgresql: "9.4"

services:
  - postgresql

install:
  - pip install tox
  - pip install python-dotenv  # Required for "restore_schemas"

before_script:
  - psql -c 'create database opentrials_api_test;' -U postgres
  - psql -c 'create database opentrials_warehouse_test;' -U postgres
  - make restore_schemas

script:
  - make test
